### ISSUE TITLE
Windows AWS Credential File Path Template Expectation

### ISSUE THREAD

**Issue by hangtime79** [iann0036/vscode-aws-cloudshell#6]
I have tried multiple versions of using Windows file paths to point to my AWS Credentials but I am invariably coming up against the following error:

`mainThreadExtensionService.ts:65 [[object Object]]Profile c:/Users/gscase/.aws/credentials could not be found or parsed in shared credentials file.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
_doInvokeHandler @ rpcProtocol.ts:396
_invokeHandler @ rpcProtocol.ts:330
_receiveRequest @ rpcProtocol.ts:269
_receiveOneMessage @ rpcProtocol.ts:208
(anonymous) @ rpcProtocol.ts:90
fire @ event.ts:525
fire @ ipc.net.ts:449
_receiveMessage @ ipc.net.ts:785
(anonymous) @ ipc.net.ts:642
fire @ event.ts:525
acceptChunk @ ipc.net.ts:191
(anonymous) @ ipc.net.ts:191
t @ ipc.net.ts:925
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 Error: Profile c:/Users/gscase/.aws/credentials could not be found or parsed in shared credentials file.
	at resolveProfileData (c:\Users\gscase\.vscode\extensions\iann0036.aws-cloudshell-0.1.6\node_modules\@aws-sdk\credential-provider-ini\dist\cjs\index.js:80:11)
	at c:\Users\gscase\.vscode\extensions\iann0036.aws-cloudshell-0.1.6\node_modules\@aws-sdk\credential-provider-ini\dist\cjs\index.js:29:59
	at async c:\Users\gscase\.vscode\extensions\iann0036.aws-cloudshell-0.1.6\node_modules\@aws-sdk\property-provider\dist\cjs\memoize.js:26:26
	at async c:\Users\gscase\.vscode\extensions\iann0036.aws-cloudshell-0.1.6\out\Utils.js:24:21`

I have tried variations with no luck.

- c:/Users/<user>/.aws/credentials
- file//c:/Users/<user>/.aws/credentials
- file:///C:/Users/gscase/.aws/credentials
- C:\Users\gscase\.aws\credentials

### Current Setup
session-manager-plugin --version
1.2.30.0

### VSCode Information
![image](https://user-images.githubusercontent.com/2651677/103068831-2475fd00-4612-11eb-81f6-2e2d1522950e.png)

Am I missing something?

**Comment by iann0036** [comment]
Do you have your AWS CLI credentials configured? (i.e. can you do an `aws sts get-caller-identity`) ?
